name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          # Kita perpanjang pencarian datanya menjadi 30 hari
          plugin_habits_days: 90
          plugin_habits_facts: no
          # Menginstruksikan bot untuk mengambil 200 event terakhirmu
          plugin_habits_from: 200
          config_timezone: Asia/Jakarta
