name: Metrics
on:
  # Mengupdate grafik otomatis setiap hari pada jam 00:00
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Memanggil kunci token yang baru dibuat
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Mematikan info standar agar hanya muncul grafik Radar
          base: ""
          
          # Pengaturan Plugin Habits (Grafik Produktivitas)
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: no
          
          config_timezone: Asia/Jakarta
